aws:
  key: some-arn
azure:
  tenant_id: <TENANT_ID>
  client_secret: <CLIENT_SECRET>
  client_id: <CLIENT_ID>
  vault_uri: <VAULT_URI>
clerk:
  jwks_url: <JWKS URL>
  webhook_secret: <webhook_signing_secret>
git:
  repository: https://github.com/flanksource/sass-dev
  user: flankbot
  base: main
  branch: main
  pull_request:
    assignees: []
    reviewers:
      - moshloop
  github_token: <GH_TOKEN>
  kustomization: '{{ .cluster }}/kustomization.yml'
